version: v0.11.1

dsn: memory

serve:
  public:
    base_url: http://localhost:4433/
    cors:
      enabled: true
      allowed_origins:
        - http://localhost:3000
        - http://localhost:3002
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Content-Type
        - X-CSRF-Token
        - Cookie
      exposed_headers:
        - Content-Type
        - Set-Cookie
      allow_credentials: true

  admin:
    base_url: http://localhost:4434/

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE

selfservice:
  default_browser_return_url: http://localhost:3000/auth/login
  allowed_return_urls:
    - http://localhost:3000/auth/login
    - http://localhost:3002/auth/login

  methods:
    oidc:
      enabled: true
      config:
        providers:
          - id: google
            provider: google
            client_id: ${GOOGLE_CLIENT_ID}
            client_secret: ${GOOGLE_CLIENT_SECRET}
            mapper_url: file:///etc/config/kratos/google.jsonnet
            scope:
              - openid
              - profile
              - email

    password:
      enabled: true

  flows:
    registration:
      ui_url: http://localhost:3000/auth/registration
      lifespan: 10m

    login:
      ui_url: http://localhost:3000/auth/login
      lifespan: 10m

log:
  level: debug
  format: text

hashers:
  argon2:
    parallelism: 1
    memory: 128MB
    iterations: 2
    salt_length: 16
    key_length: 16

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: "smtp://test:test@mailslurper:1025/?skip_ssl_verify=true"
